export const TOGGLE_CHECKBOX_STUDIES = 'TOGGLE_CHECKBOX_STUDIES'
export const UPDATE_EDUCATION = 'UPDATE_EDUCATION'
export const UPDATE_YEARS_OF_EXPERIENCE = 'UPDATE_YEARS_OF_EXPERIENCE'
export const UPDATE_MIN_HOURS = 'UPDATE_MIN_HOURS'
export const UPDATE_MAX_HOURS = 'UPDATE_MAX_HOURS'
export const TOGGLE_SUMMARY_DISPLAY = 'TOGGLE_SUMMARY_DISPLAY'

